name: CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend/recipe-front
    steps:
      - name: Git checkout
      - uses: actions/checkout@v3
      
      - name: Use Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: npm install
        run: npm install
        
      - name: lint
        run: npm run lint
        
      - name: jest
        run: npm test
        
  backend:
    runs-on: ubuntu-latest
    env: 
      TEST_DB: 'mongodb+srv://localhost:27017'
    defaults:
      run:
        working-directory: Backend/recipe-back
        
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '5.0'
          
      - name: npm install
        run: npm install
        
      - name: lint
        run: npm run lint
        
      - name: jest
        run: npm test
